services:
  postgres:
    container_name: postgres-sql-jwt
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: <your_db>
    volumes:
      - postgres:/data/postgres
    ports:
      - 5431:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-jwt
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local